apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: cat-stage

images:
- digest: sha256:73949cf5b96a068f2fa7268b561dbac5086764266e360201ea15f5e3f1fb6291
  name: quay.io/rbrhssa/quarkus-grumpycat:latest
  newName: quay.io/rbrhssa/quarkus-grumpycat:v0.7-test
- digest: sha256:6c191bb1cfeab23992982dd704421a041f7dfd1c0bee7c53d13b7f047444b13a
  name: quay.io/wpernath/grumpycat-melonjs:latest
  newName: quay.io/rbrhssa/grumpycat-melonjs:v0.6.5
- digest: sha256:5b234e919571f30a231aa7f7fdd25503dc68092c9a6eebe34de1e7427941fc4f
  name: quay.io/wpernath/quarkus-grumpycat:latest
  newName: quay.io/rbrhssa/quarkus-grumpycat:v0.6.7.Test1

# generate a configmap 
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server service
  # 
  # Grumpycat Server configmap, just point to the internal service name of the kafka service
configMapGenerator:
- literals:
  - APPLICATION_BASESERVERURL=http://cat-server-cat-stage.apps.cluster-fxmxz.fxmxz.sandbox452.opentlc.com/
  name: client-config
- literals:
  - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092
  name: server-config
