apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: cat-dev

images:
- digest: sha256:88b07ca24c61a76ad98049da13fc2839e2cc97d05046d49f79db6b5fdf946fa3
  name: quay.io/rbrhssa/quarkus-grumpycat:latest
  newName: quay.io/rbrhssa/quarkus-grumpycat:latest

# generate a configmap 
  # Cat - Client ConfigMap, note that the client app runs entirely on the browser, 
  # so we need to use the external URL of the grumpycat server service
  # 
  # Grumpycat Server configmap, just point to the internal service name of the kafka service
configMapGenerator:
- literals:
  - APPLICATION_BASESERVERURL=http://cat-server-cat-dev.apps.cluster-fxmxz.fxmxz.sandbox452.opentlc.com/
  - WORKSHOP_TEST_VAR=Welcome in this Bootcamp!
  name: client-config
- literals:
  - KAFKA_BOOTSTRAP_SERVERS=grumpy-kafka-kafka-bootstrap:9092
  name: server-config
